finish translate plugin tcp_conn

diff --git a/tcp_conn/tcp_conn b/tcp_conn/tcp_conn
--- a/tcp_conn/tcp_conn
+++ b/tcp_conn/tcp_conn
@@ -1,13 +1,50 @@
 #!/usr/bin/env bash
 
 
+
 BASE_DIR="/usr/local/eminfo/"
-if [ -f "${BASE_DIR}/bin/include" -a -s "${BASE_DIR}/bin/include" ]; then
-        source ${BASE_DIR}/bin/include 2>&-
+# === LOAD GETTEXT.SH FILE
+if [ -f "/usr/bin/gettext.sh"  -a -s "/usr/bin/gettext.sh" ]; then
+        source "/usr/bin/gettext.sh" 2>&1
+        rc=$?
+        [ "$rc" != "0" ] && {
+                echo -en "{unknown}:{str}:{load [/usr/bin/gettext.sh] failed with status $rc}"
+                exit 3
+        }   
 else
-        echo -en "{unknown}:{str}:{include file not exists or empty}"
-	exit 3
+        echo -en "{unknown}:{str}:{[/usr/bin/gettext.sh] not exists or empty, maybe gettext not installed. exit}"
+        exit 3
 fi
+
+# === LOAD INCLUDE FILE
+if [ -f "${BASE_DIR}/bin/include" -a -s "${BASE_DIR}/bin/include" ]; then
+        source ${BASE_DIR}/bin/include 2>&- 
+else    
+        echo -en "{unknown}:{str}:{include file not exists or empty}"
+        exit 3
+fi
+
+# === SET TEXTDOMAINDIR TEXTDOMAIN
+if [ -d "${LOCALE_DIR}" -a -r "${LOCALE_DIR}" ]; then
+        export TEXTDOMAINDIR="${LOCALE_DIR}"
+        export TEXTDOMAIN="tcp_conn"
+else    
+        echo -en "{unknown}:{str}:{locale directory [${LOCALE_DIR}] not exist or accessable, exit}"
+        exit 3
+fi
+
+
+# === SET GLOBAL LOCALE
+glocale=$(read_eminfo_config tcp_conn locale)
+if [ -z "${glocale}" ]; then
+        export LANG="${LANG}"           ## read from sysenv
+elif [ "${glocale}" == "zh_CN" -o "${glocale}" == "zh_CN.UTF-8" -o "${glocale}" == "zh" ]; then
+        export LANG="zh_CN.UTF-8"
+elif [ "${glocale}" == "en_US" -o "${glocale}" == "en_US.UTF-8" -o "${glocale}" == "en" ]; then
+        export LANG="en_US.UTF-8"
+fi
+
+
 
 show_help(){
 cat <<EOF
@@ -104,23 +141,23 @@ check_single(){
   }
 
   if [ -z "${total}" -o ! -z "${total//[0-9]}" ]; then
-	local output=" $(html_yellow "check [${s_port}:${limit}]: return: [${total}] is not numberic") ### Maybe port: [${s_port}] not listening ### "
+	local output=" $(html_yellow "$(eval_gettext "check [\${s_port}:\${limit}]: return: [\${total}] is not numberic")") ### $(eval_gettext "Maybe port: [\${s_port}] not listening") ### "
 	return_code=2
   else
-	[ "$(echo " ${total} >= ${limit} " | bc 2>&-)" == "1" ] && {
-		local output="$(html_red "Total: [${total}] >= Limit: [${limit}]" ) ### "
+	if [ "$(echo " ${total} >= ${limit} " | bc 2>&-)" == "1" ]; then
+		local output="$(html_red "$(eval_gettext "Total: [\${total}] >= Limit: [\${limit}]")") ### "
 		return_code=1
-	} || {
-		local output="Total: [${total}] < Limit: [${limit}] ### "
+	else
+		local output="$(eval_gettext "Total: [\${total}] < Limit: [\${limit}]") ### "
 		return_code=0
-	}
-  	local output="${output} $(echo -e "${conn_stat} ### ### IP Connect Stat: ### ${ip_stat} ### " | sed -e 's/$/ ### /g' | tr -d '\n' )"
+	fi
+  	local output="${output} $(echo -e "${conn_stat} ### ### $(gettext "IP Connect Stat:") ### ${ip_stat} ### " | sed -e 's/$/ ### /g' | tr -d '\n' )"
   fi
   echo -e "${output}"
   return ${return_code}
 }
 
-  local result=" ### Check List: [${port_list}] ### ### "
+  local result=" ### $(eval_gettext "Check List: [\${port_list}]") ### ### "
   local oknum=0 errnum=0 unknum=0 total=0
   local statfile="/tmp/.check_tcpconn_num.statfile.eminfo"
   /bin/netstat -an > "${statfile}" 2>&-
@@ -128,7 +165,7 @@ check_single(){
 	EXIT_STATUS=${STATE_UNKNOWN};
         LEVEL="unknown";
         TYPE="str";
-        CONTENT="netstat file: [${statfile}] not exist or empty."
+        CONTENT="$(eval_gettext "netstat file: [\${statfile}] not exist or empty.")"
         return
   }
 
@@ -146,10 +183,10 @@ check_single(){
   do
 	((total++))
 	local port="${port_num%%:*}" num="${port_num##*:}"
-	result="${result} ### Check Tcp-Port [${port}], Uplimit [${num}] ### "
+	result="${result} ### $(eval_gettext "Check Tcp-Port [\${port}], Uplimit [\${num}]") ### "
 	[ -z "${port}" -o ! -z "${port//[0-9]}" -o -z "${num}" -o ! -z "${num//[0-9]}" ] && {
 		((unknum++))
-		result="${result} $(html_red "[${port_num}] is invalid: [${port}] or [${num}] not numberic") ### "
+		result="${result} $(html_red "$(eval_gettext "[\${port_num}] is invalid: [\${port}] or [\${num}] not numberic")") ### "
 		continue 1
 	}
 
@@ -170,19 +207,19 @@ check_single(){
 	EXIT_STATUS=${STATE_CRITICAL};
 	LEVEL="crit";
 	TYPE="str";
-	CONTENT="TCP-Connection Number Check CRITICAL | ${errnum}/${total} check failed. | "${result}" "
+	CONTENT="$(gettext "TCP-Connection Number Check CRITICAL") | $(eval_gettext "\${errnum}/\${total} check failed.") | "${result}" "
   } || {
 	[ "${oknum}" == "${total}" ] && {
 		EXIT_STATUS=${STATE_OK};
 		LEVEL="ok";
 		TYPE="str";
-		CONTENT="TCP-Connection Number Check OK | ${oknum}/${total} check success. | "${result}" "
+		CONTENT="$(gettext "TCP-Connection Number Check OK") | $(eval_gettext "\${oknum}/\${total} check success.") | "${result}" "
 	} || {
 		[ "${unknum}" != "0" ] && {
 			EXIT_STATUS=${STATE_UNKNOWN};
 			LEVEL="unknown";
 			TYPE="str";
-			CONTENT="TCP-Connection Number Check UNKNOWN | ${unknum}/${total} check unknown. | "${result}" "
+			CONTENT="$(eval_gettext "TCP-Connection Number Check UNKNOWN") | $(eval_gettext "\${unknum}/\${total} check unknown.") | "${result}" "
 		}
 	}
   } 
