finish translate for plugin disk_fs

diff --git a/disk_fs/disk_fs b/disk_fs/disk_fs
--- a/disk_fs/disk_fs
+++ b/disk_fs/disk_fs
@@ -2,12 +2,46 @@
 
 
 BASE_DIR="/usr/local/eminfo/"
-if [ -f "${BASE_DIR}/bin/include" -a -s "${BASE_DIR}/bin/include" ]; then
-        source ${BASE_DIR}/bin/include 2>&-
+# === LOAD GETTEXT.SH FILE
+if [ -f "/usr/bin/gettext.sh"  -a -s "/usr/bin/gettext.sh" ]; then
+        source "/usr/bin/gettext.sh" 2>&1
+        rc=$?
+        [ "$rc" != "0" ] && {
+                echo -en "{unknown}:{str}:{load [/usr/bin/gettext.sh] failed with status $rc}"
+                exit 3
+        }
 else
-        echo -en "{unknown}:{str}:{include file not exists or empty}"
-	exit 3
+        echo -en "{unknown}:{str}:{[/usr/bin/gettext.sh] not exists or empty, maybe gettext not installed. exit}"
+        exit 3
 fi
+
+# === LOAD INCLUDE FILE
+if [ -f "${BASE_DIR}/bin/include" -a -s "${BASE_DIR}/bin/include" ]; then
+        source ${BASE_DIR}/bin/include 2>&- 
+else        
+        echo -en "{unknown}:{str}:{include file not exists or empty}"
+        exit 3
+fi
+
+# === SET TEXTDOMAINDIR TEXTDOMAIN
+if [ -d "${LOCALE_DIR}" -a -r "${LOCALE_DIR}" ]; then
+        export TEXTDOMAINDIR="${LOCALE_DIR}"
+        export TEXTDOMAIN="disk_fs"
+else        
+        echo -en "{unknown}:{str}:{locale directory [${LOCALE_DIR}] not exist or accessable, exit}"
+        exit 3
+fi
+
+# === SET GLOBAL LOCALE
+glocale=$(read_eminfo_config disk_fs locale)
+if [ -z "${glocale}" ]; then
+        export LANG="${LANG}"           ## read from sysenv
+elif [ "${glocale}" == "zh_CN" -o "${glocale}" == "zh_CN.UTF-8" -o "${glocale}" == "zh" ]; then
+        export LANG="zh_CN.UTF-8"
+elif [ "${glocale}" == "en_US" -o "${glocale}" == "en_US.UTF-8" -o "${glocale}" == "en" ]; then
+        export LANG="en_US.UTF-8"
+fi
+
 
 show_help(){
 cat <<EOF
@@ -64,7 +98,7 @@ check(){
         EXIT_STATUS=${STATE_UNKNOWN};
         LEVEL="unknown";
         TYPE="str";
-        CONTENT="Util: [/sbin/tune2fs] not prepared.";
+        CONTENT="$(gettext "Util: [/sbin/tune2fs] not prepared.")";
         return
   }
 
@@ -72,14 +106,14 @@ check(){
 	EXIT_STATUS=${STATE_UNKNOWN};
 	LEVEL="unknown";
 	TYPE="str";
-	CONTENT="File: [/etc/mtab] not prepared.";
+	CONTENT="$(gettext "File: [/etc/mtab] not prepared.")";
 	return
   }
 
   local result= mpoint= warnnum=0  unknnum=0
 
-  result="FSTYPE: [${filesystem_fstype}] ### ###"
-  result="${result} ### FileSystem Stat ### "
+  result="$(eval_gettext "FSTYPE: [\${filesystem_fstype}]") ### ###"
+  result="${result} ### $(gettext "FileSystem Stat") ### "
   for t in `echo "${filesystem_fstype}"`
   do
 	devices=$(awk '($3~/\<'${t}'\>/){print $1}' "/etc/mtab" 2>&-|tr '\n' ' ')
@@ -92,24 +126,24 @@ check(){
 			continue
 		}
 		if [ -z "${stat}" ]; then
-			result="${result} (${t}) ${d} -> unknown ### ";
+			result="${result} $(eval_gettext "(\${t}) \${d} -> unknown") ### ";
 			((unknnum++))
 		elif [ "${stat}" == "clean" ]; then
-			result="${result} (${t}) ${d} -> clean ###"
+			result="${result} $(eval_gettext "(\${t}) \${d} -> clean") ###"
 		else
 			((warnnum++))
-			result="${result} $(html_red "(${t}) ${d} -> ${stat}") ###"
+			result="${result} $(html_red "$(eval_gettext "(\${t}) \${d} -> \${stat}")") ###"
 		fi
   	done
   done
 
-  result="${result} ### IO Test ###"
+  result="${result} ### $(gettext "IO Test") ###"
   for t in `echo "${filesystem_fstype}"`
   do  
         mpoint=$(awk '($3~/\<'${t}'\>/){print $2}' "/etc/mtab" 2>&-|tr '\n' ' ')
         for m in `echo "${mpoint}"`
         do  
-                ioerr=$(/bin/touch "${m}/.disk_fs.iotest" 2>&1 1>/dev/null | tr -d '\r\n')
+                ioerr=$(/bin/touch "${m}/.disk_fs.iotest" 2>&1 1>/dev/null)
   		rc=$?
                 # output data and exit if MODE=1
                 [ "${MODE}" == "1" -a "${action}" == "io" ] && {
@@ -122,9 +156,10 @@ check(){
                         continue
                 }   
                 if [ "${rc}" == "0" ]; then
-                        result="${result} (${t}) ${m} -> iotest Success ### "
+                        result="${result} $(eval_gettext "(\${t}) \${m} -> iotest Success") ### "
                 else
-                        result="${result} $(html_red "(${t}) ${m} -> iotest warning: ${ioerr}") ### "
+			ioerr=$(echo -e "${ioerr}" | tr -d '\r\n')
+                        result="${result} $(html_red "$(eval_gettext "(\${t}) \${m} -> iotest warning: \${ioerr}")") ### "
 			((warnnum++))
                 fi  
         done
@@ -137,18 +172,18 @@ check(){
 	EXIT_STATUS=${STATE_WARNING};
 	LEVEL="warn";
 	TYPE="str";
-	CONTENT="IO/FS Check WARNING | ${warnnum} check failed | ${result} "
+	CONTENT="$(gettext "IO/FS Check WARNING") | $(eval_gettext "\${warnnum} check failed") | ${result} "
   } || {
 	[ "${unknnum}" -gt "0" ] && {
 		EXIT_STATUS=${STATE_UNKNOWN};
 		LEVEL="unknown";
 		TYPE="str";
-		CONTENT="IO/FS Check UNKNOWN | ${unknnum} check unknown | ${result} "
+		CONTENT="$(gettext "IO/FS Check UNKNOWN") | $(eval_gettext "${unknnum} check unknown") | ${result} "
 	} || {
 		EXIT_STATUS="${STATE_OK}"
 		LEVEL="ok"
 		TYPE="str"
-		CONTENT="IO/FS Check OK | fsstat,iotest check success | ${result} "
+		CONTENT="$(gettext "IO/FS Check OK") | $(gettext "fsstat,iotest check success") | ${result} "
 	}
   }
 }
