finish translate sysload, bugfix on sysload

diff --git a/sysload/sysload b/sysload/sysload
--- a/sysload/sysload
+++ b/sysload/sysload
@@ -1,13 +1,50 @@
 #!/usr/bin/env bash
 
 
+
 BASE_DIR="/usr/local/eminfo/"
-if [ -f "${BASE_DIR}/bin/include" -a -s "${BASE_DIR}/bin/include" ]; then
-        source ${BASE_DIR}/bin/include 2>&-
+# === LOAD GETTEXT.SH FILE
+if [ -f "/usr/bin/gettext.sh"  -a -s "/usr/bin/gettext.sh" ]; then
+        source "/usr/bin/gettext.sh" 2>&1
+        rc=$?
+        [ "$rc" != "0" ] && {
+                echo -en "{unknown}:{str}:{load [/usr/bin/gettext.sh] failed with status $rc}"
+                exit 3
+        }   
 else
-        echo -en "{unknown}:{str}:{include file not exists or empty}"
-	exit 3
+        echo -en "{unknown}:{str}:{[/usr/bin/gettext.sh] not exists or empty, maybe gettext not installed. exit}"
+        exit 3
 fi
+
+# === LOAD INCLUDE FILE
+if [ -f "${BASE_DIR}/bin/include" -a -s "${BASE_DIR}/bin/include" ]; then
+        source ${BASE_DIR}/bin/include 2>&- 
+else    
+        echo -en "{unknown}:{str}:{include file not exists or empty}"
+        exit 3
+fi
+
+# === SET TEXTDOMAINDIR TEXTDOMAIN
+if [ -d "${LOCALE_DIR}" -a -r "${LOCALE_DIR}" ]; then
+        export TEXTDOMAINDIR="${LOCALE_DIR}"
+        export TEXTDOMAIN="sysload"
+else    
+        echo -en "{unknown}:{str}:{locale directory [${LOCALE_DIR}] not exist or accessable, exit}"
+        exit 3
+fi
+
+
+# === SET GLOBAL LOCALE
+glocale=$(read_eminfo_config sysload locale)
+if [ -z "${glocale}" ]; then
+        export LANG="${LANG}"           ## read from sysenv
+elif [ "${glocale}" == "zh_CN" -o "${glocale}" == "zh_CN.UTF-8" -o "${glocale}" == "zh" ]; then
+        export LANG="zh_CN.UTF-8"
+elif [ "${glocale}" == "en_US" -o "${glocale}" == "en_US.UTF-8" -o "${glocale}" == "en" ]; then
+        export LANG="en_US.UTF-8"
+fi
+
+
 
 show_help(){
 cat <<EOF
@@ -40,12 +77,12 @@ TYPE=   	### { str| file }
 CONTENT=        ### { strings | /path/to/result.file }
 
 # Read plugin config value here
-average_cpuload_uplimit=$(read_eminfo_config sysload average_cpuload_uplimit)
+load_uplimit=$(read_eminfo_config sysload load_uplimit)
 
 # if null return STATE_UNKNOWN.
 
 # if null or invalid set default.
-[ -z "${average_cpuload_uplimit}" -o ! -z "${average_cpuload_uplimit//[0-9]}" ] && average_cpuload_uplimit=3
+[ -z "${load_uplimit}" -o ! -z "${load_uplimit//[0-9.]}" ] && load_uplimit=10
 
 # check function here
 check(){
@@ -53,39 +90,38 @@ check(){
 	EXIT_STATUS=${STATE_UNKNOWN};
 	LEVEL="unknown";
 	TYPE="str";
-	CONTENT="FILE: [/proc/loadavg] or [/proc/cpuinfo] not prepared."
+	CONTENT="$(gettext "FILE: [/proc/loadavg] or [/proc/cpuinfo] not prepared.")"
 	return
   }
 
   # collect data
-  local cpunum=$(awk '($1~/^processor/){t++}END{print t}' /proc/cpuinfo)
   local loadave=$( cut -d" " -f1 /proc/loadavg 2>&1 )
 
   [ -z "${loadave}" -o ! -z "${loadave//[0-9.]}" ] && {
         EXIT_STATUS=${STATE_UNKNOWN};
         LEVEL="unknown";
         TYPE="str";
-        CONTENT="Retuen is not numberic: ["${loadave}"]"
+        CONTENT="$(eval_gettext "Retuen is not numberic: [\${loadave}]")"
         return
   }
 
   # output data and exit if MODE=1
   [ "${MODE}" == "1" ] && {
-	echo "${cpunum} ${loadave}"
+	echo "${loadave}"
 	exit
   }
 
   # output plugin format data if MODE=0
-  if [ "$(echo  "${loadave} >= (${cpunum} * ${average_cpuload_uplimit})" | bc 2>&-)" == "1" ]; then
+  if [ "$(echo  "${loadave} >= ${load_uplimit}" | bc 2>&-)" == "1" ]; then
 	EXIT_STATUS=${STATE_WARNING};
 	LEVEL="warn";
 	TYPE="str";
-	CONTENT="System Load Check CRITICAL | load [${loadave} >= $((${average_cpuload_uplimit}*${cpunum}))] | processor number: ${cpunum}, average load limit: ${average_cpuload_uplimit}"
+	CONTENT="$(gettext "System Load Check CRITICAL") | $(eval_gettext "load [\${loadave} >= \${load_uplimit}]")"
   else
 	EXIT_STATUS=${STATE_OK};
 	LEVEL="ok";
 	TYPE="str";
-	CONTENT="System Load Check OK | load [${loadave} <= $((${average_cpuload_uplimit}*${cpunum}))] | processor number: ${cpunum}, average load limit: ${average_cpuload_uplimit}"
+	CONTENT="$(gettext "System Load Check OK") | $(eval_gettext "load [\${loadave} <= \${load_uplimit}]")"
   fi
 }
 
