adjust autorpm for plugins

diff --git a/rpm_build/autorpm b/rpm_build/autorpm
--- a/rpm_build/autorpm
+++ b/rpm_build/autorpm
@@ -5,12 +5,11 @@ basedir=${path%/*}
 
 show_help(){
 cat << HELP 
-	${0##*/}
-	${0##*/}  help
-	${0##*/}  clean
-	${0##*/}  {plugin}
-	${0##*/}  basic tarball
-	${0##*/}  mail  tarball
+	${0##*/}  help			# show help
+	${0##*/}  clean			# do cleaning job
+	${0##*/}  {plugin}		# make rpm for single plugin
+	${0##*/}  basic tarball		# make rpm for {basic-group} plugins
+	${0##*/}  mail  tarball		# make rpm for {mail-group} plugins
 HELP
 exit 0
 }
@@ -28,59 +27,22 @@ clean
 	exit 1
 }
 
-if [ -z "${1}" ]; then
-  specfile="${path}/spec_files/mole-plugin.spec"
-  plugins=( 
-	cpu_usage
-	disk_fs
-	disk_iostat
-	disk_raid
-	disk_space
-	dns_svr
-	fdnum
-	http_svr
-	imap_svr
-	emp_mailqueue
-	memcache_perf
-	memory
-	mysql_dump
-	mysql_ping
-	mysql_repl
-	nfs_svr
-	notify_oom
-	notify_syslogin
-	pop_svr
-	port
-	process
-	remote_mailtest
-	smtp_svr
-	ssd
-	sysload
-	# system_dyninfo
-	# system_fixinfo
-	tcp_conn
-	traffic
-  )
-else
-
-  if [ "${1}" == "help" -o "${1}" == "-h" -o "${1}" == "?" ]; then
+# process cli args
+if [ -z "${1}" -o "${1}" == "help" -o "${1}" == "-h" -o "${1}" == "?" ]; then
 	show_help
-  elif [ "${1}" == "basic" -a "${2}" == "tarball" ]; then
+elif [ "${1}" == "basic" -a "${2}" == "tarball" ]; then
 	TARMODE=1
-  elif [ "${1}" == "mail"  -a "${2}" == "tarball" ]; then
+elif [ "${1}" == "mail"  -a "${2}" == "tarball" ]; then
 	TARMODE=2
-  else
-  	if [ -d "${basedir}/${1}" ]; then
-		specfile="${path}/spec_files/${1}.spec"
-		plugins=( ${1} )
-  	else
-		echo "plugin directory [$1] not exist"
-		exit 1
-  	fi
-  fi
-
+else
+	show_help
 fi
 
+# init {specfile} / {plugins}
+specfile=
+plugins=()
+
+# set {specfile} / {plugins}
 if [ "${TARMODE}" == "1" ]; then	# reset specfile and plugins
   specfile="${path}/spec_files/mole-plugin.spec"
   plugins=( 
@@ -94,8 +56,6 @@ if [ "${TARMODE}" == "1" ]; then	# reset specfile and plugins
        	port
  	process
        	sysload
-       	# system_dyninfo
-       	# system_fixinfo
        	tcp_conn
        	traffic
   )
@@ -111,12 +71,34 @@ elif [ "${TARMODE}" == "2" ]; then	# reset specfile and plugins
   )
 fi
 
-name=$(awk -F: '($1~/Name/){print $2}' "${specfile}" 2>&-|tr -d ' \t')
-version=$(awk -F: '($1~/Version/){print $2}' "${specfile}" 2>&-|tr -d ' \t')
-source0=$(awk -F: '($1~/Source0/){print $2}' "${specfile}" 2>&-|tr -d ' \t')
+# check {specfile} / {plugins}
+if [ -z "${specfile}" ]; then
+	echo "spec file not defined";
+	exit 1;
+else
+	if [ -f "${specfile}" -a -s "${specfile}" ]; then
+		:
+	else
+		echo "spec file: [${specfile}] not exists or empty";
+		exit 1;
+	fi
+fi
+if [ ${#plugins[*]} -eq 0 ]; then
+	echo "array plugins not defined";
+	exit 1;
+fi
 
+# set {name} / {version} / {source0}
+name=$(/bin/awk -F: '($1~/Name/){print $2}' "${specfile}" 2>&-|tr -d ' \t')
+version=$(/bin/awk -F: '($1~/Version/){print $2}' "${specfile}" 2>&-|tr -d ' \t')
+source0=$(/bin/awk -F: '($1~/Source0/){print $2}' "${specfile}" 2>&-|tr -d ' \t')
 
-mkdir -p "${path}"/SOURCES/${name}-${version}
+if [ -z "${name}" -o -z "${version}" -o -z "${source0}" ]; then
+	echo "[name/version/source0] not defined";
+	exit 1;
+fi
+
+/bin/mkdir -p "${path}"/SOURCES/${name}-${version}
 if [ "${TARMODE}" == "2" ]; then
 	/bin/cp -arf "${basedir}"/upgrade/esop-plugingroup-mail_upgrade "${path}"/SOURCES/${name}-${version}/
 fi
@@ -130,13 +112,30 @@ do
 		}
 	done
 done
-cd "${path}"/SOURCES/
-tar -czf "${source0}" ${name}-${version}
-rm -rf "${path}"/SOURCES/${name}-${version}
+if cd "${path}"/SOURCES/; then
+	if tar -czf "${source0}" ${name}-${version}; then
+		if rm -rf "${path}"/SOURCES/${name}-${version}; then
+			:
+		else
+			echo "remove at-last directory failed";
+			exit 1;
+		fi
+	else
+		echo "make tar as {source0} failed";
+		exit 1;
+	fi
+else
+	echo "change into SOURCES/ failed";
+	exit 1;
+fi
+
+# if mode = {tarball}, end at here 
 if [ "${TARMODE}" != "" ]; then
   echo ""${path}"/SOURCES/${source0}"
   exit 0
 fi
+
+# following codes always no need any longer
 /bin/cp -a "${specfile}" "${path}"/SPECS/
 
 cat > ~/.rpmmacros <<EOF
